<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  ServerName wiki.mci.org
  
  # Devise URL rewrite rules
  RewriteEngine on
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-d
  RewriteRule ^(.*)$ %{DOCUMENT_ROOT}/index.php [L]
  
  DocumentRoot /home/www-data/wiki.mci.org
  <Directory /home/www-data/wiki.mci.org>
  	Options +FollowSymLinks
    AllowOverride All
  	Order allow,deny
  	allow from all
  </Directory>
 
  LogLevel warn
  ErrorLog /var/log/apache2/wiki.mci.org.error.log
  CustomLog /var/log/apache2/wiki.mci.org.access.log combined
</VirtualHost>
