# General
MCI_CI=
MCI_CI_URL=https
MCI_CI_IPADDR=127.0.0.1
MCI_CI_PORT=8070

# Jenkins
MCI_CI_JENKINS_SITE=
MCI_CI_JENKINS_WEBSERVER=apache2
MCI_CI_JENKINS_DBENGINE=
MCI_CI_JENKINS_VERSION_INSTALLED=1.508
MCI_CI_JENKINS_VERSION_UPDATED=
