# General


# MYSQL
MCI_DBENGINE_MYSQL_ROOTPW=pwmysql
MCI_DBENGINE_MYSQL_HOST=localhost
MCI_DBENGINE_MYSQL_PORT=3306

# POSTGRESQL
MCI_DBENGINE_PGSQL_ROOTPW=pwpgsql
MCI_DBENGINE_PGSQL_HOST=localhost
MCI_DBENGINE_PGSQL_PORT=5432
