# General
MCI_LMS=
MCI_LMS_URL=https
MCI_LMS_IPADDR=127.0.0.1
MCI_LMS_PORT=80

# Sentry
MCI_LMS_SENTRY_SITE=
MCI_LMS_SENTRY_URL=
MCI_LMS_SENTRY_WEBSERVER=apache2
MCI_LMS_SENTRY_DBENGINE=postgresql
MCI_LMS_SENTRY_PGSQL_VERSION_REQUIRED=
MCI_LMS_SENTRY_PGSQL_DBNAME=
MCI_LMS_SENTRY_PGSQL_DBUSER=sentry
MCI_LMS_SENTRY_PGSQL_DBPW=pwsentry
