# General
MCI_SSO=
MCI_SSO_URL=https
MCI_SSO_IPADDR=127.0.0.1
MCI_SSO_PORT=80

# MIGO
MCI_SSO_MIGO_SITE=
MCI_SSO_MIGO_URL=
MCI_SSO_MIGO_WEBSERVER=apache2
MCI_SSO_MIGO_DBENGINE=postgresql
MCI_SSO_MIGO_POSTGRESQL_VERSION_REQUIRED=9.1
